import NavBar from "./components/navbar";
import "./globals.css";

export const metadata = {
  title: "Tulsi Vanstone Ceramics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
